### ISSUE TITLE
The timer doesn't really works

### ISSUE THREAD

**Issue by rpesche** [sepandhaghighi/mytimer#2]
#### Description

The timer is not correct. It fails counting time.
Launching a 20 minutes timer takes 19 minutes and 41 seconds instead of 20 minutes

#### Steps/Code to Reproduce

You can try this :

```
$ time mytimer --minute=20
```

#### Expected Behavior

We must get something like this :

```
mytimer --minute=20  2.36s user 0.99s system 0% cpu 20:00.00 total
```

#### Actual Behavior

When testing I got this :

```
mytimer --minute=20 --countdown  2.36s user 0.99s system 0% cpu 19:41.35 total
```

**Comment by sepandhaghighi** [comment]
@rpesche Hi
Thanks for the report 💯
You are right. The amount of delay in each iteration consists of 2 parts:
1. Conditions and modules performance
2. Sleep amount

In the first version, I fixed the sleep amount to `0.98` seconds to compensate the first part delay (it's not a suitable method!)
Now, I have updated the functions, if it's possible please check the `accuracy` branch and inform me.

Best Regards
SH

**Comment by alirezazolanvari** [comment]
> @sadrasabouri @alirezazolanvari
> 
> Is it possible for you to test this repo (`accuracy` branch) in your system and give me the report?
> 
> Windows (Powershell):
> 
> ```
> Measure-Command {mytimer --minute=1 --second=40}
> ```
> 
> Linux/MacOS:
> 
> ```
> time mytimer --minute=1 --second=40
> ```

Hello @sepandhaghighi,

The result of the test on Windows was as follows:

```
Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 40
Milliseconds      : 823
Ticks             : 1008231027
TotalDays         : 0.00116693405902778
TotalHours        : 0.0280064174166667
TotalMinutes      : 1.680385045
TotalSeconds      : 100.8231027
TotalMilliseconds : 100823.1027
```

**Comment by sadrasabouri** [comment]
> ```
> time mytimer --minute=1 --second=40
> ```

Hi @sepandhaghighi 
After counting for 1':40'' with `art` font, it showed:
```
      ___         __         __    ___    
     / _ \   ()  /  )  ()   /. |  / _ \   
    ( (_) )       )(       (_  _)( (_) )  
     \___/   ()  (__)  ()    (_)  \___/   

 _____             _  _ 
| ____| _ __    __| || |
|  _|  | '_ \  / _` || |
| |___ | | | || (_| ||_|
|_____||_| |_| \__,_|(_)
                        


real	1m45.910s
user	0m0.799s
sys	0m0.227s
```
and my system details are:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by sepandhaghighi** [comment]
@sadrasabouri Are these results for the `accuracy` branch? 
If the answer is yes, would you please measure the time with a standard stopwatch? (without loading and end times, from `0:0:0` to `0:1:40`).

**Comment by sadrasabouri** [comment]
> @sadrasabouri Are these results for the `accuracy` branch? If the answer is yes, would you please measure the time with a standard stopwatch? (without loading and end times, from `0:0:0` to `0:1:40`).

I am sure, but I will try again in the coming days.
I am also pretty sure about its timing, it was almost accurate.

**Comment by sadrasabouri** [comment]
I checked it again. The result was same for a standard stopwatch.
