### ISSUE TITLE
Auto alignment

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/mytimer#47]
#### Description
The feature of auto alignment adjusts the layout of the display based on the size of the terminal.

**Comment by sepandhaghighi** [comment]
@sadrasabouri I believe we can close this issue. What's your opinion? If you agree, please close it 📕

**Comment by sadrasabouri** [comment]
> @sadrasabouri I believe we can close this issue. What's your opinion? If you agree, please close it 📕

Yes, I guess given that it's not straight-forward to implement, and it's also not in our main scope we can skip adding it for now. I close it with this comment.
