### ISSUE TITLE
Enter `q` or `q+enter` to quit (new feature)

### ISSUE THREAD

**Issue by ghazalrafiei** [sepandhaghighi/mytimer#61]
#### Description
This is a suggestion for new feature. Implement a feature so that the program terminates by entering `q+enter` or just a `q`, instead of `ctrl+c`.

**Comment by sepandhaghighi** [comment]
Nice 🔥 
However, I am concerned about implementing this feature without using a third-party library! Do you have any idea?

I believe that we can enhance the user experience by taking the first step toward it by:

1. Add a message about how to exit using `Ctrl + C`
2. Handle `KeyboardInterrupt`

**Comment by sadrasabouri** [comment]
Thanks @ghazalrafiei for opening this issue.
If you have any plan for working on this issue, please update this thread.

**Comment by ghazalrafiei** [comment]
Unfortunately, I am currently unable to work on this feature.

**Comment by sepandhaghighi** [comment]
I will handle this one 🔥

**Comment by sepandhaghighi** [comment]
@sadrasabouri Would you be interested in taking care of this matter?

**Comment by sadrasabouri** [comment]
> @sadrasabouri Would you be interested in taking care of this matter?

Sure.

**Comment by sepandhaghighi** [comment]
@sadrasabouri On you 🔥
