### ISSUE TITLE
Move the timer to the centre of the terminal window (new feature)

### ISSUE THREAD

**Issue by ghazalrafiei** [sepandhaghighi/mytimer#62]
#### Description
Since the timer is using all of the terminal window, it would look nicer if it is in the centre of the window and the rest of the display is not wasted.

**Comment by sepandhaghighi** [comment]
Good idea 🔥 
It's related to the terminal size and specifically pertains to issue #47.

**Comment by sadrasabouri** [comment]
We released the new version introducing `v-shift` and `h-shift` and now we're going to work on #47 which is fairly similar to this one. Therefor this issue is now closed.
