### ISSUE TITLE
Zero padding

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/mytimer#66]
#### Description
Print `01:02:23` instead of `1:2:23`
To avoid display stretching, implementing this solution will prove to be helpful.

**Comment by sepandhaghighi** [comment]
@sadrasabouri Would you like to take care of this task? Let me know if you are interested.

**Comment by sadrasabouri** [comment]
> @sadrasabouri Would you like to take care of this task? Let me know if you are interested.

Sure
