### ISSUE TITLE
[Feature]: Add `--set-on` flag

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/mytimer#97]
### Describe the feature you want to add

Add a `--set-on` flag to set the timer until a specific time.

```shell
mytimer --hour=15 --minute=30 --set-on
```
This will run timer until `15:30` from now

**Comment by sepandhaghighi** [comment]
@sadrasabouri Are you interested in addressing this issue?

**Comment by sadrasabouri** [comment]
> @sadrasabouri Are you interested in addressing this issue?

Yes I am. I will self-assign it to myself. Will talk about the timeline for adding this feature in our weekly.
